version: "3.8"

services:
  servidor:
    build: .
    container_name: chat_servidor
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    command: ["go", "run", "servidor.go"] # Executa o servidor

  cliente1:
    build: .
    container_name: cliente_1
    depends_on:
      - servidor # Garante que o servidor inicie primeiro
    volumes:
      - .:/app
    command: ["go", "run", "cliente1.go"] # Executa o cliente 1

  cliente2:
    build: .
    container_name: cliente_2
    depends_on:
      - servidor
    volumes:
      - .:/app
    command: ["go", "run", "cliente2.go"] # Executa o cliente 2

networks:
  default:
    driver: bridge