services:
  servidor:
    build: .
    container_name: servidor
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    command: ["go", "run", "servidor.go"]

  # Define um único serviço de cliente para criar a imagem
  cliente:
    build: .
    volumes:
      - .:/app
    command: ["go", "run", "cliente.go"]
